name: ⭐Trigger sync

on:
  repository_dispatch:
    types: [main_updated]

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'HaeJungg/ci-cd-copied'
    steps:
      - run: echo 'sync'
