name: ⭐Trigger sync

on:
  repository_dispatch:
    types: [main_updated]

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    if: github.repository == 'HaeJungg/ci-cd-copied'
    steps:
      - uses: actions/checkout@v4
      - name: ✨Sync fork 
        run: |
          git remote add upstream https://github.com/subject-test-01/ci-cd.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
